### ISSUE TITLE
Not verifying SSL Certificate?

### ISSUE THREAD

**Issue by shunwen** [treeder/rest_client#10]
Hi @treeder ,

Just a quick question.

My project was using your `rest_client` and working fine. Recently I switched to the official `rest-client` and started getting `RestClient::SSLCertificateNotVerified` error from my internal server, maybe it's because the certificate was self-signed. Is this difference something you changed on purpose?

Thanks!

**Comment by treeder** [comment]
I don't recall changing anything like that on purpose, but it could be related to this commit: https://github.com/treeder/rest_client/commit/ae72fa75555ae8a20b51402461fb3adeb6bb3f50

**Comment by shunwen** [comment]
@treeder Thanks, I played around with that option after your suggestion, but even without specifying `ssl_version` to `SSLv23` the connection still falls back to `SSLv3` in my case. So that's not a problem I guess. 

I think the screenshot below is the code causing this trouble:
![kaleidoscope_ _request_rb__rest-client____request_rb__rest_client_](https://cloud.githubusercontent.com/assets/485385/6456904/a88a555c-c1af-11e4-8aef-40f00a724d82.png)

Looks like without `verify_ssl` option, your version by default skips the verification, while the current official version will set it to `VERIFY_PEER`.

**Comment by treeder** [comment]
Maybe they changed it, not sure. Should pass in verify_ssl => false it looks like.

**Comment by shunwen** [comment]
@treeder Yes, I am using `verify_ssl: false` option now. Just wondering what's the difference verifying ssl or not, and why it was defaulted to false before and got changed now. Anyway, thanks for your help!
